version: '4.0'

actions:
  generate_dataset:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py --output output/dataset.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset.csv.gz

  run_analysis:
    run: r:latest analysis/pregnancy_analysis.R
    needs: [generate_dataset]
    inputs:
      dataset: output/dataset.csv.gz
    outputs:
      highly_sensitive:
        analysis_results: output/analysis_results.rds

  generate_report:
    run: r:latest -e "rmarkdown::render('analysis/analysis_report.Rmd', output_file='output/analysis_report.html')"
    needs: [run_analysis]
    inputs:
      analysis_results: output/analysis_results.rds
    outputs:
      highly_sensitive:
        report: output/analysis_report.html
